version: "3.7"
services:
  blockchain:
    build: ./ganache
    volumes:
      - ./shared/:/shared/
  contract-deployer:
    build: ./contracts
    depends_on:
      - "blockchain"
    environment:
      - BLOCKCHAIN_HOST=blockchain
      - BLOCKCHAIN_PORT=8545
    volumes:
      - ./shared/:/shared/
    command: ./wait-for-it.sh -s blockchain:8545 -- yarn start
  backend:
    build: ./providerService
    depends_on:
      - "contract-deployer"
    ports:
      - "8080:8080"
    environment:
      - KEYS_PATH=./shared/keyfile.json
      - ADDRESSES_PATH=./shared/addresses.json
      - BLOCKCHAIN_URI=http://blockchain:8545
      - CONTRACT_DIRECTORY=./shared/contracts
    volumes:
      - ./shared/:/shared/
    command: ./wait-for-it.sh -s blockchain:8545 -- bash -c 'until [[ $$(wc -l < shared/addresses.json) -ge 6 ]]; do sleep 1; done; ./gradlew bootRun'
  webapp:
    build: ./webapp
    ports:
      - "3000:80"
    depends_on:
      - "contract-deployer"
