version: "3.7"
services:
  blockchain:
    build: ./ganache
    volumes:
      - ./shared:/shared
  contract-deployer:
    build: ./contracts
    depends_on:
      - "blockchain"
    environment:
      - BLOCKCHAIN_HOST=blockchain
      - BLOCKCHAIN_PORT=8545
    volumes:
      - ./shared:/shared
    command: ./wait-for-it.sh -s blockchain:8545 -- yarn start
  backend:
    build: ./providerService
    depends_on:
      - "contract-deployer"
    ports:
      - "9753:8080"
    environment:
      - KEYS_PATH=./shared/keyfile.json
      - ADDRESSES_PATH=./shared/addresses.json
    volumes:
      - ./shared:/shared
    command: ./wait-for-it.sh -s blockchain:8545 -- bash -c 'until [[ $$(wc -l < shared/addresses.json) -ge 6 ]]; do sleep 1; done; java -jar /app.jar'
  webapp:
    build: ./webapp
    ports:
      - "8080:80"
